import Topnav from "@/components/topnav/Topnav";
import "./globals.css";
import Bootstrap from "@/components/Bootstartp";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Providers } from "@/rit/provider";
import { ToastContainer } from "react-toastify";
import Aos from "@/components/Aos";
import "aos/dist/aos.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="ture">
        <Providers>
          <Bootstrap />
          <Topnav />
          <Navbar />
          {children}
          <Footer />
        </Providers>
        <Aos />
        <ToastContainer autoClose={1000} position="top-center" />
      </body>
    </html>
  );
}
