import Topnav from "@/components/topnav/Topnav";
import "./globals.css";
import Bootstrap from "@/components/Bootstartp";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Providers } from "@/rit/provider";
import Pixel_home from "@/components/pixel/Pixel_home";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="ture">
        <Providers>
          {/* <Pixel_home /> */}
          <Bootstrap />
          <Topnav />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
